apiVersion: 1

contactPoints:
  - orgId: 1
    name: Order Tracker responder
    receivers:
      - uid: order-tracker-responder-webhook
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://host.docker.internal:8001/alerts
          httpMethod: POST
          maxAlerts: 0
